import React,{useEffect,useState} from 'react';
import ReactModal from '../common/ReactModal.jsx';
import {useApp} from '../../context/AppContext.jsx';
import {login} from '../../services/auth.js';
import {supabase} from '../../services/supabase.js';
export default function LoginModal(){
 const {openModal,closeModal,notify,modal}=useApp(); const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{if(modal?.name==='login'){setEmail('');setPassword('');setShow(false);setError('');setLoading(false)}},[modal?.name]);
 const submit=async e=>{e.preventDefault();if(loading)return;const em=email.trim().toLowerCase();if(!em||!password)return setError('Please enter your email and password.');if(!/^\S+@\S+\.\S+$/.test(em))return setError('Please enter a valid email address.');setLoading(true);const {error}=await login(em,password);setLoading(false);if(error)return setError(error.message||'Sign in failed. Check your details and try again.');closeModal();notify('Welcome back. Your private space is ready.')};
 const google=async()=>{if(loading)return;setLoading(true);const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}});if(error){setLoading(false);setError(error.message||'Google sign-in could not start.')}};
 const reset=async()=>{const em=email.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(em))return setError('Enter your email first, then choose Forgot password.');setLoading(true);const {error}=await supabase.auth.resetPasswordForEmail(em,{redirectTo:window.location.origin});setLoading(false);if(error)return setError(error.message);notify('If that account exists, a password reset link has been sent.','info')};
 return <ReactModal name="login" title="" className="p13-login-modal"><div className="login-layout"><aside className="login-art"><div/><section><small>VIBORAQ · PAKISTAN</small><h2>Come back to the<br/><em>people who feel right.</em></h2><p>Your profile, conversations and next connection are waiting.</p><blockquote>“A quieter way to meet someone.”</blockquote></section></aside><form className="login-form" onSubmit={submit} autoComplete="off"><div className="auth-brand"><b>V</b><div><strong>VIBORAQ</strong><small>PRIVATE DATING SPACE</small></div></div><span className="auth-kicker">WELCOME BACK</span><h2>Sign in to your <em>space.</em></h2><p className="auth-sub">Continue where you left off—securely and simply.</p><label>Email address</label><div className="auth-input"><span>✉</span><input value={email} onChange={e=>{setEmail(e.target.value);setError('')}} type="email" autoComplete="off" placeholder="you@example.com"/></div><div className="label-row"><label>Password</label><button type="button" onClick={reset}>Forgot password?</button></div><div className="auth-input"><span>⌑</span><input value={password} onChange={e=>{setPassword(e.target.value);setError('')}} type={show?'text':'password'} autoComplete="new-password" placeholder="Your password"/><button type="button" onClick={()=>setShow(v=>!v)}>{show?'Hide':'Show'}</button></div>{error&&<div className="auth-error"><b>!</b>{error}</div>}<button className="auth-submit" disabled={loading}>{loading?'Signing you in…':'Sign in securely'}<b>→</b></button><div className="auth-or"><i/>or continue with<i/></div><button type="button" className="google-btn" onClick={google} disabled={loading}><b>G</b> Continue with Google</button><div className="create-link">New to ViboraQ? <button type="button" onClick={()=>openModal('onboarding',{reset:true})}>Create your free profile</button></div><small className="privacy">🔒 Never share your password. Your account stays private.</small></form></div></ReactModal>
}