import React from 'react';
import { useApp } from '../context/AppContext.jsx';

const people=[
{name:'Areeba',age:23,city:'Lahore · DHA Phase 5',vibe:'Coffee · Art · Study',cat:'coffee',img:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=85&w=900&auto=format&fit=crop'},
{name:'Hamza',age:26,city:'Lahore · Gulberg III',vibe:'Gym · Gaming · Tech',cat:'gym',img:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=85&w=900&auto=format&fit=crop'},
{name:'Maham',age:24,city:'Islamabad · F-7',vibe:'Books · Travel · Coffee',cat:'coffee',img:'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=85&w=900&auto=format&fit=crop'},
{name:'Ali',age:27,city:'Karachi · Clifton',vibe:'Fitness · Food · Sports',cat:'sports',img:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=85&w=900&auto=format&fit=crop'}];
const filters=[['all','All people','✦'],['coffee','Coffee & culture','☕'],['gym','Fitness','◉'],['gaming','Gaming','⌁'],['sports','Sports','◇']];

function Explore({filter,setFilter,openModal,notify}){
 const list=filter==='all'?people:people.filter(p=>p.cat===filter);
 return <section className="p13-page"><div className="p13-live"><i/> <div><b>ViboraQ Discovery</b><small>Explore people by interests, city and vibe.</small></div><em>LIVE</em></div>
 <div className="p13-head"><div><span className="p13-kicker">DISCOVER</span><h1>Find a vibe that <em>feels natural.</em></h1><p>Browse profiles, notice shared interests and start with a conversation—not a swipe.</p></div></div>
 <div className="p13-filters">{filters.map(([k,t,ic])=><button className={filter===k?'active':''} key={k} onClick={()=>setFilter(k)}>{ic} {t}</button>)}</div>
 <div className="p13-grid">{list.map(p=><article className="p13-card" key={p.name}><div className="p13-card-photo" style={{backgroundImage:`url(${p.img})`}}><span className="online">●</span><span className="verified">✦ Verified</span><button onClick={()=>notify(`${p.name} saved to your favourites.`)}>♡</button></div><div className="p13-card-body"><h3>{p.name}, {p.age}</h3><small>📍 {p.city}</small><p>{p.vibe}</p><button className="connect" onClick={()=>openModal('icebreaker',{person:p.name})}>Start a conversation <b>→</b></button></div></article>)}</div></section>;
}
function Profile({profile,session,openModal,signOut}){
 const u=session?.user,name=profile.nickname||u?.user_metadata?.nickname||u?.email?.split('@')[0]||'ViboraQ member',email=profile.email||u?.email||'',city=profile.city||u?.user_metadata?.city||'Pakistan';
 return <section className="p13-page p13-profile"><div className="profile-hero"><div className="avatar" style={profile.avatarUrl?{backgroundImage:`url(${profile.avatarUrl})`}:{}}>{!profile.avatarUrl&&name[0]?.toUpperCase()}</div><div><span className="p13-kicker">YOUR PRIVATE SPACE</span><h1>{name}</h1><p>{city} · {email}</p></div><div className="profile-actions"><button onClick={()=>openModal('edit')}>Edit profile</button><button onClick={signOut}>Sign out</button></div></div><div className="profile-cols"><article><span>YOUR PROFILE</span><h3>Let your personality do the talking.</h3><p>{profile.bio||'Add a short introduction so people can understand your vibe before they connect.'}</p><button onClick={()=>openModal('edit')}>Complete profile →</button></article><article><span>YOUR INTERESTS</span><h3>{profile.interests?.length?'Things you enjoy':'Add what you love'}</h3><div className="interest-list">{(profile.interests?.length?profile.interests:['Coffee','Travel','Music']).slice(0,10).map(x=><i key={x}>{x}</i>)}</div></article></div><div className="privacy-note">🔒 <div><b>Your account is private by default.</b><small>Only information you choose to share is shown to other members.</small></div></div></section>;
}
export default function Dashboard(){
 const {session,authReady,activeTab,setActiveTab,activeFilter,setActiveFilter,openModal,profile,signOut,notify}=useApp();
 if(!authReady||!session)return null;
 const tabs=[['explore','Discover','✦'],['chats','Messages','♡'],['vip','Elite','♢'],['profile','Profile','◉']];
 return <div className="p13-dashboard"><header className="p13-dash-head"><button onClick={()=>setActiveTab('explore')} className="brand">✦ <b>VIBORAQ</b><small>PAKISTAN</small></button><div><span className="private">● Private space</span><button className="complete" onClick={()=>openModal('edit')}>Complete profile</button></div></header><main className="p13-scroll">{activeTab==='explore'&&<Explore filter={activeFilter} setFilter={setActiveFilter} openModal={openModal} notify={notify}/>} {activeTab==='chats'&&<section className="p13-page simple"><span className="p13-kicker">CONVERSATIONS</span><h1>Your conversations, <em>without the noise.</em></h1><p>Once you connect with someone, your conversations will appear here.</p><div className="empty">♡<h3>Your inbox is ready.</h3><small>Explore profiles and start a thoughtful conversation.</small></div></section>} {activeTab==='vip'&&<section className="p13-page simple vip"><span className="p13-kicker">VIBORAQ ELITE</span><h1>More room to <em>connect.</em></h1><p>Priority discovery and richer profile tools, designed for members who want more.</p><div className="vip-card"><div><b>COMING SOON</b><h3>Elite membership</h3><small>Payment features will be connected after the core community is stable.</small></div><button onClick={()=>openModal('sub',{featureKey:'vip'})}>Explore VIP</button></div></section>} {activeTab==='profile'&&<Profile profile={profile} session={session} openModal={openModal} signOut={signOut}/>}</main><nav className="p13-nav">{tabs.map(([k,t,ic])=><button className={activeTab===k?'active':''} onClick={()=>setActiveTab(k)} key={k}><span>{ic}</span>{t}</button>)}</nav></div>;
}