import React,{useState} from 'react';
import {useApp} from '../context/AppContext.jsx';
const pics=[
['Areeba','Lahore','https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=85&w=1000&auto=format&fit=crop'],
['Maham','Islamabad','https://images.unsplash.com/photo-1517841905240-472988babdf9?q=85&w=1000&auto=format&fit=crop'],
['Hamza','Lahore','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=85&w=1000&auto=format&fit=crop']];
const reviews=[['A.','Lahore','I wanted somewhere calmer than the usual dating apps. The profile-first idea makes conversations feel much more natural.'],['M.','Islamabad','I can actually see someone’s interests before deciding to say hello. It feels thoughtful rather than noisy.'],['H.','Karachi','Simple, polished and focused on conversation. That is the kind of dating experience I was looking for.']];
export default function LandingPage(){
 const {session,authReady,openModal}=useApp(); const [r,setR]=useState(0); if(authReady&&session)return null;
 return <main className="p13-landing"><div className="p13-bg"><i/><i/><i/></div>
 <nav className="p13-land-nav"><button className="p13-logo" onClick={()=>scrollTo({top:0,behavior:'smooth'})}><b>V</b><strong>VIBORAQ</strong><small>PAKISTAN</small></button><div className="p13-links"><a href="#experience">Experience</a><a href="#discover">Discover</a><a href="#stories">Stories</a></div><div className="p13-nav-actions"><button onClick={()=>openModal('login')}>Sign in</button><button className="join" onClick={()=>openModal('onboarding',{reset:true})}>Join free ↗</button></div></nav>
 <section className="p13-hero"><div className="p13-copy"><span className="eyebrow">♡ A more intentional way to meet</span><h1>Meet someone who<br/><em>feels like home.</em></h1><p>ViboraQ is a premium space for meaningful connections across Pakistan—built around personality, shared interests and conversations that actually go somewhere.</p><div className="hero-actions"><button className="main-cta" onClick={()=>openModal('onboarding',{reset:true})}>Create my free profile <b>→</b></button><button className="text-cta" onClick={()=>openModal('login')}>I already have an account</button></div><div className="trust"><span>✦ Profile-first</span><span>♡ Conversation-led</span><span>⌁ Privacy-minded</span></div></div><div className="hero-art"><div className="portrait p1" style={{backgroundImage:`url(${pics[0][2]})`}}/><div className="portrait p2" style={{backgroundImage:`url(${pics[2][2]})`}}/><div className="match">♡ <div><b>Potential connection</b><small>Shared interests · Lahore</small></div></div><div className="online">● 24 people exploring</div><i className="ring a"/><i className="ring b"/></div></section>
 <section className="ribbon"><span>REAL PEOPLE</span><i/> <span>SHARED INTERESTS</span><i/> <span>GOOD CONVERSATIONS</span><i/> <span>MADE FOR PAKISTAN</span></section>
 <section id="experience" className="p13-section"><div className="section-head"><span>THE EXPERIENCE</span><h2>Dating should feel <em>less noisy.</em></h2><p>Everything is designed to help you notice the person behind the profile.</p></div><div className="feature-grid">{[['01','♡','Profiles with personality','Interests, city, preferences and a little story give you something real to start with.'],['02','✦','Conversations first','Connect with intention and let the first message be about something you actually share.'],['03','⌁','A calmer space','Focused controls and privacy-minded account design keep the experience comfortable.']].map(x=><article key={x[0]}><b>{x[0]}</b><i>{x[1]}</i><h3>{x[2]}</h3><p>{x[3]}</p></article>)}</div></section>
 <section id="discover" className="p13-section discover"><div className="section-head"><span>DISCOVER</span><h2>There is more than one way to <em>click.</em></h2><p>A preview of the visual language your live community will use.</p></div><div className="discover-grid">{pics.map((p,i)=><article key={p[0]}><div style={{backgroundImage:`url(${p[2]})`}}><span>Online</span><button>♡</button></div><h3>{p[0]}</h3><small>{p[1]} · Shared interests</small></article>)}</div></section>
 <section id="stories" className="p13-section stories"><div className="section-head"><span>COMMUNITY STORIES</span><h2>A good connection deserves a <em>good story.</em></h2><p>Design-stage testimonials are placeholders until verified member reviews are available.</p></div><article className="review"><b>“</b><blockquote>{reviews[r][2]}</blockquote><footer><span><strong>{reviews[r][0]}</strong><small>{reviews[r][1]} · Design preview</small></span><em>★★★★★</em></footer><div className="review-nav"><button onClick={()=>setR((r+2)%3)}>←</button>{reviews.map((_,i)=><button className={i===r?'on':''} key={i} onClick={()=>setR(i)}/>) }<button onClick={()=>setR((r+1)%3)}>→</button></div></article></section>
 <section className="p13-how"><div className="how-photo" style={{backgroundImage:`url(${pics[1][2]})`}}><b>♡</b></div><div><span className="eyebrow">HOW IT WORKS</span><h2>From hello to <em>something real.</em></h2>{[['01','Create your profile','Tell people what makes you you.'],['02','Discover your people','Notice shared interests and compatible vibes.'],['03','Start the conversation','Send a thoughtful first message and see where it goes.']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><div><strong>{x[1]}</strong><p>{x[2]}</p></div></div>)}</div></section>
 <section className="final"><span>YOUR NEXT CHAPTER</span><h2>Someone worth meeting<br/><em>could be one hello away.</em></h2><p>Join free. Build your profile. Take it at your own pace.</p><button className="main-cta" onClick={()=>openModal('onboarding',{reset:true})}>Create my free profile →</button></section>
 <footer className="p13-footer"><div className="p13-logo"><b>V</b><strong>VIBORAQ</strong><small>PAKISTAN</small></div><span>© 2026 ViboraQ · Meaningful connections.</span><div><button onClick={()=>openModal('login')}>Sign in</button><button onClick={()=>openModal('onboarding',{reset:true})}>Create account</button></div></footer></main>
}